### ISSUE TITLE
Doesn't Autocomplete on "--" or "var(-"

### ISSUE THREAD

**Issue by marti6jm** [yeion7/styled-global-variables-autocomplete#1]
This extension is almost exactly what I was looking for but I immediately found it a bit of a hassle to work with because if I go to keep typing my variable name, by typing the second dash, the autocomplete closes out. Similarly if I type out "var()" myself and start typing dashes, the autocomplete doesn't show up.

I don't know if you're open to contributions at all, but I had gone ahead and forked your extension and was able to solve these issues:
https://github.com/marti6jm/styled-global-variables-autocomplete

And I can open up a PR if so - though I do apologize in advance my formatter made a number of smaller spacing changes to your files as well.

**Comment by yeion7** [comment]
Hey, PRs are welcome, thanks for finding a solution
